// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Artist struct {
	ID       int64      `json:"id"`
	Name     string     `json:"name"`
	Artworks []*Artwork `json:"artworks"`
}

type ArtistUpdateAction struct {
	SetName *SetArtistName `json:"setName"`
}

type Artwork struct {
	ID     int64   `json:"id"`
	Title  string  `json:"title"`
	Artist *Artist `json:"artist"`
}

type ArtworkUpdateAction struct {
	SetTitle  *SetArtworkTitle  `json:"setTitle"`
	SetArtist *SetArtworkArtist `json:"setArtist"`
}

type SetArtistArtWorks struct {
	ArtworksID []int64 `json:"artworksID"`
}

type SetArtistName struct {
	Name string `json:"name"`
}

type SetArtworkArtist struct {
	ArtistID int64 `json:"artistID"`
}

type SetArtworkTitle struct {
	Title string `json:"title"`
}
